// 0002 — the create-table migration for every project domain resource.
import type { AutomationStudioSchemaMigration } from "../../schema-migrations.ts";

export const AUTOMATION_STUDIO_PROJECT_DOMAIN_RESOURCE_MIGRATION: AutomationStudioSchemaMigration = {
  id: "0002_domain_resource_tables",
  statements: [
    `create table hierarchy_entries (
      entry_id text primary key,
      parent_entry_id text,
      kind text not null,
      owner_id text not null,
      display_name text not null,
      sort_key text not null default '',
      depth integer not null default 0 check (depth >= 0),
      path_key text not null,
      is_system integer not null default 0 check (is_system in (0, 1)),
      is_deleted integer not null default 0 check (is_deleted in (0, 1)),
      revision integer not null default 1 check (revision > 0),
      created_at_ms integer not null,
      updated_at_ms integer not null
    )`,
    `create table workspace_preferences (
      user_id text not null,
      preference_key text not null,
      value_json text not null,
      revision integer not null default 1 check (revision > 0),
      updated_at_ms integer not null,
      primary key (user_id, preference_key)
    )`,
    `create table flows (
      flow_id text primary key,
      parent_flow_id text,
      owning_subflow_id text,
      name text not null,
      description text not null default '',
      scope_kind text not null,
      scope_id text,
      visibility text not null default 'private' check (visibility in ('private', 'project', 'domain', 'global')),
      origin text not null default 'user' check (origin in ('user', 'recording', 'adaptation', 'import', 'system')),
      source_mode text not null default 'visual' check (source_mode in ('visual', 'code', 'hybrid')),
      status text not null default 'draft' check (status in ('draft', 'active', 'archived', 'deleted')),
      graph_revision integer not null default 1 check (graph_revision > 0),
      settings_revision integer not null default 1 check (settings_revision > 0),
      compiled_revision integer check (compiled_revision is null or compiled_revision > 0),
      created_at_ms integer not null,
      updated_at_ms integer not null,
      deleted_at_ms integer
    )`,
    `create table flow_settings (
      flow_id text primary key,
      execution_defaults_json text not null,
      training_json text not null,
      adaptation_json text not null,
      llm_json text not null,
      safety_json text not null,
      revision integer not null default 1 check (revision > 0),
      updated_at_ms integer not null
    )`,
    `create table flow_ports (
      port_id text primary key,
      flow_id text not null,
      direction text not null check (direction in ('input', 'output')),
      name text not null,
      value_type text not null,
      required integer not null default 0 check (required in (0, 1)),
      default_value_json text,
      description text not null default '',
      sort_key text not null default '',
      revision integer not null default 1 check (revision > 0)
    )`,
    `create table flow_variables (
      variable_id text primary key,
      flow_id text not null,
      name text not null,
      value_type text not null,
      initial_value_json text,
      description text not null default '',
      sort_key text not null default '',
      revision integer not null default 1 check (revision > 0)
    )`,
    `create table flow_errors (
      error_id text primary key,
      flow_id text not null,
      code text not null,
      description text not null default '',
      metadata_json text not null default '{}',
      revision integer not null default 1 check (revision > 0)
    )`,
    `create table graph_partitions (
      partition_id text primary key,
      flow_id text not null,
      grid_x integer not null,
      grid_y integer not null,
      min_x real not null,
      min_y real not null,
      max_x real not null,
      max_y real not null,
      node_count integer not null default 0 check (node_count >= 0),
      edge_count integer not null default 0 check (edge_count >= 0),
      revision integer not null default 1 check (revision > 0),
      updated_at_ms integer not null
    )`,
    `create table graph_nodes (
      node_id text primary key,
      flow_id text not null,
      partition_id text,
      definition_id text not null,
      definition_version text not null,
      label text not null,
      description text not null default '',
      x real not null,
      y real not null,
      width real not null check (width >= 0),
      height real not null check (height >= 0),
      z_index integer not null default 0,
      disabled integer not null default 0 check (disabled in (0, 1)),
      parameter_values_json text not null default '{}',
      metadata_json text not null default '{}',
      revision integer not null default 1 check (revision > 0),
      created_at_ms integer not null,
      updated_at_ms integer not null,
      deleted_at_ms integer
    )`,
    `create table graph_edges (
      edge_id text primary key,
      flow_id text not null,
      source_node_id text not null,
      target_node_id text not null,
      source_port_id text,
      target_port_id text,
      label text not null default '',
      metadata_json text not null default '{}',
      revision integer not null default 1 check (revision > 0),
      created_at_ms integer not null,
      updated_at_ms integer not null,
      deleted_at_ms integer
    )`,
    `create table flow_regions (
      region_id text primary key,
      flow_id text not null,
      partition_id text,
      name text not null,
      kind text not null,
      bounds_json text not null,
      metadata_json text not null default '{}',
      revision integer not null default 1 check (revision > 0)
    )`,
    `create table flow_region_handoffs (
      handoff_id text primary key,
      flow_id text not null,
      from_region_id text not null,
      to_region_id text not null,
      contract_json text not null,
      revision integer not null default 1 check (revision > 0)
    )`,
    `create table graph_revisions (
      revision_id text primary key,
      flow_id text not null,
      revision_number integer not null check (revision_number > 0),
      parent_revision integer,
      author_id text,
      source text not null,
      operation_count integer not null default 0 check (operation_count >= 0),
      snapshot_object_id text,
      digest text not null,
      message text not null default '',
      created_at_ms integer not null
    )`,
    `create table graph_operations (
      operation_id text primary key,
      revision_id text not null,
      ordinal integer not null check (ordinal >= 0),
      operation_kind text not null,
      entity_kind text not null,
      entity_id text not null,
      before_json text,
      after_json text
    )`,
    `create table subflows (
      subflow_id text primary key,
      parent_flow_id text not null,
      graph_flow_id text not null,
      parent_category_id text,
      name text not null,
      description text not null default '',
      role text not null default '',
      status text not null default 'draft' check (status in ('draft', 'active', 'archived', 'deleted')),
      input_mapping_json text not null default '[]',
      output_mapping_json text not null default '[]',
      approval_override text check (approval_override is null or approval_override in ('adaptive', 'manual_approval', 'disabled')),
      revision integer not null default 1 check (revision > 0),
      created_at_ms integer not null,
      updated_at_ms integer not null,
      deleted_at_ms integer
    )`,
    `create table subflow_categories (
      category_id text primary key,
      flow_id text not null,
      parent_category_id text,
      name text not null,
      sort_key text not null default '',
      revision integer not null default 1 check (revision > 0),
      created_at_ms integer not null,
      updated_at_ms integer not null
    )`,
    `create table routers (
      router_id text primary key,
      flow_id text not null,
      fallback_kind text not null default 'none' check (fallback_kind in ('none', 'subflow', 'error')),
      fallback_subflow_id text,
      revision integer not null default 1 check (revision > 0),
      created_at_ms integer not null,
      updated_at_ms integer not null
    )`,
    `create table router_groups (
      group_id text primary key,
      router_id text not null,
      name text not null,
      sort_key text not null default '',
      revision integer not null default 1 check (revision > 0)
    )`,
    `create table router_routes (
      route_id text primary key,
      router_id text not null,
      group_id text,
      name text not null,
      priority integer not null default 0,
      enabled integer not null default 1 check (enabled in (0, 1)),
      condition_kind text not null,
      condition_json text not null,
      target_kind text not null check (target_kind in ('subflow', 'flow', 'error', 'none')),
      target_subflow_id text,
      revision integer not null default 1 check (revision > 0),
      created_at_ms integer not null,
      updated_at_ms integer not null
    )`,
    `create table instructions (
      instruction_id text primary key,
      title text not null,
      body_object_id text,
      inline_body text,
      requirement text not null default 'guidance' check (requirement in ('guidance', 'required', 'forbidden')),
      status text not null default 'active' check (status in ('draft', 'active', 'archived', 'deleted')),
      priority integer not null default 0,
      content_digest text not null,
      revision integer not null default 1 check (revision > 0),
      created_at_ms integer not null,
      updated_at_ms integer not null,
      deleted_at_ms integer
    )`,
    `create table instruction_scopes (
      instruction_id text not null,
      scope_kind text not null check (scope_kind in ('global', 'project', 'flow', 'router', 'subflow', 'node', 'error')),
      project_id text,
      flow_id text,
      router_id text,
      subflow_id text,
      node_id text,
      error_code text
    )`,
    `create table instruction_tags (
      instruction_id text not null,
      tag text not null,
      primary key (instruction_id, tag)
    )`,
    `create table instruction_bindings (
      binding_id text primary key,
      owner_kind text not null,
      owner_id text not null,
      instruction_id text not null,
      sort_key text not null default '',
      enabled integer not null default 1 check (enabled in (0, 1)),
      revision integer not null default 1 check (revision > 0)
    )`,
    `create table effective_instruction_cache (
      scope_digest text primary key,
      instruction_revision integer not null check (instruction_revision > 0),
      object_id text not null,
      created_at_ms integer not null
    )`,
    `create table runtime_runs (
      run_id text primary key,
      flow_id text not null,
      flow_revision integer not null check (flow_revision > 0),
      compiled_artifact_id text,
      status text not null check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
      trigger_kind text not null,
      queued_at_ms integer not null,
      started_at_ms integer,
      finished_at_ms integer,
      action_count integer not null default 0 check (action_count >= 0),
      effect_count integer not null default 0 check (effect_count >= 0),
      error_count integer not null default 0 check (error_count >= 0),
      adaptation_count integer not null default 0 check (adaptation_count >= 0),
      last_event_sequence integer not null default 0 check (last_event_sequence >= 0),
      input_object_id text,
      output_object_id text,
      error_object_id text,
      updated_at_ms integer not null
    )`,
    `create table runtime_event_chunks (
      chunk_id text primary key,
      run_id text not null,
      first_sequence integer not null check (first_sequence >= 0),
      last_sequence integer not null check (last_sequence >= first_sequence),
      event_count integer not null check (event_count >= 0),
      byte_count integer not null check (byte_count >= 0),
      object_id text not null,
      sha256 text not null,
      closed integer not null default 0 check (closed in (0, 1)),
      created_at_ms integer not null
    )`,
    `create table recordings (
      recording_id text primary key,
      name text not null,
      task_id text,
      domain_id text,
      status text not null check (status in ('recording', 'completed', 'failed', 'cancelled')),
      started_at_ms integer not null,
      ended_at_ms integer,
      event_count integer not null default 0 check (event_count >= 0),
      action_count integer not null default 0 check (action_count >= 0),
      state_snapshot_count integer not null default 0 check (state_snapshot_count >= 0),
      thumbnail_object_id text,
      updated_at_ms integer not null
    )`,
    `create table recording_event_chunks (
      chunk_id text primary key,
      recording_id text not null,
      first_sequence integer not null check (first_sequence >= 0),
      last_sequence integer not null check (last_sequence >= first_sequence),
      event_count integer not null check (event_count >= 0),
      byte_count integer not null check (byte_count >= 0),
      object_id text not null,
      sha256 text not null,
      closed integer not null default 0 check (closed in (0, 1)),
      created_at_ms integer not null
    )`,
    `create table state_snapshots (
      snapshot_id text primary key,
      source_kind text not null,
      source_id text not null,
      sequence integer not null check (sequence >= 0),
      captured_at_ms integer not null,
      state_object_id text,
      screenshot_object_id text,
      previous_snapshot_id text,
      digest text not null,
      metadata_json text not null default '{}'
    )`,
    `create table state_paths (
      snapshot_id text not null,
      namespace text not null,
      path text not null,
      value_type text not null,
      scalar_text text,
      scalar_number real,
      scalar_boolean integer check (scalar_boolean is null or scalar_boolean in (0, 1)),
      value_object_id text,
      primary key (snapshot_id, namespace, path)
    )`,
    `create table adaptations (
      adaptation_id text primary key,
      flow_id text not null,
      subflow_id text,
      base_revision integer not null check (base_revision > 0),
      proposed_revision integer not null check (proposed_revision > 0),
      trigger text not null,
      status text not null check (status in ('draft', 'pending_approval', 'approved', 'applied', 'rejected', 'failed')),
      risk_level text not null check (risk_level in ('low', 'medium', 'high')),
      approval_mode text not null check (approval_mode in ('adaptive', 'manual_approval', 'disabled')),
      patch_object_id text not null,
      evidence_object_id text,
      created_at_ms integer not null,
      updated_at_ms integer not null,
      reviewed_at_ms integer,
      applied_at_ms integer
    )`,
    `create table adaptation_evidence (
      adaptation_id text not null,
      evidence_kind text not null,
      evidence_id text not null,
      sequence integer not null default 0,
      primary key (adaptation_id, evidence_kind, evidence_id)
    )`,
    `create table flow_publications (
      publication_id text primary key,
      flow_id text not null,
      version text not null,
      flow_revision integer not null check (flow_revision > 0),
      compiled_artifact_id text,
      digest text not null,
      status text not null check (status in ('draft', 'published', 'deprecated')),
      changelog text not null default '',
      published_at_ms integer,
      deprecated_at_ms integer
    )`,
    `create table compiled_artifacts (
      artifact_id text primary key,
      flow_id text not null,
      flow_revision integer not null check (flow_revision > 0),
      compiler_version text not null,
      object_id text not null,
      digest text not null,
      status text not null check (status in ('pending', 'ready', 'failed')),
      created_at_ms integer not null
    )`,
    `create table objects (
      object_id text primary key,
      sha256 text not null,
      media_type text not null,
      byte_count integer not null check (byte_count >= 0),
      relative_path text not null,
      compression text,
      encryption text,
      created_at_ms integer not null,
      verified_at_ms integer
    )`,
    `create table object_references (
      reference_id text primary key,
      object_id text not null,
      owner_kind text not null,
      owner_id text not null,
      purpose text not null,
      created_at_ms integer not null
    )`
  ]
};
