// The project database schema, one module per table group, in migration order.
// `foreign-key-guards.ts` is deliberately not re-exported: it is a statement
// builder these modules share, not part of the schema's public surface.
export { AUTOMATION_STUDIO_PROJECT_DOMAIN_RESOURCE_MIGRATION } from "./domain-resources.ts";
export { AUTOMATION_STUDIO_PROJECT_RELATION_INDEX_MIGRATION } from "./relation-indexes.ts";
export { AUTOMATION_STUDIO_PROJECT_MUTATION_MIGRATION } from "./mutations.ts";
export { AUTOMATION_STUDIO_PROJECT_STREAM_SPOOL_MIGRATION, AUTOMATION_STUDIO_PROJECT_EVENT_CURSOR_MIGRATION, AUTOMATION_STUDIO_PROJECT_RETENTION_MIGRATION } from "./event-streams.ts";
export { AUTOMATION_STUDIO_PROJECT_COMPILED_RUNTIME_ISOLATION_MIGRATION } from "./compiled-plans.ts";
export { AUTOMATION_STUDIO_PROJECT_ADAPTATION_EVIDENCE_MIGRATION } from "./adaptations.ts";
export { AUTOMATION_STUDIO_PROJECT_FAST_UI_QUERY_INDEX_MIGRATION } from "./ui-query-indexes.ts";
export { AUTOMATION_STUDIO_PROJECT_ROUTER_RUNTIME_SCALING_MIGRATION, AUTOMATION_STUDIO_PROJECT_ROUTER_RUNTIME_SUMMARY_DETAIL_MIGRATION, AUTOMATION_STUDIO_PROJECT_ROUTER_TARGET_REFERENCE_MIGRATION } from "./routers.ts";
export { AUTOMATION_STUDIO_PROJECT_INTERVENTION_MODE_MIGRATION } from "./flow-settings.ts";
export { AUTOMATION_STUDIO_PROJECT_RUNTIME_SUMMARY_ENVELOPE_MIGRATION } from "./runtime-runs.ts";
export { AUTOMATION_STUDIO_PROJECT_REUSABLE_LLM_CONTEXT_MIGRATION, AUTOMATION_STUDIO_PROJECT_REUSABLE_LLM_CONTEXT_AUDIT_MIGRATION, AUTOMATION_STUDIO_PROJECT_REUSABLE_LLM_CONTEXT_VALIDATION_MIGRATION } from "./reusable-llm-contexts.ts";
export { AUTOMATION_STUDIO_PROJECT_DOMAIN_TABLES, AUTOMATION_STUDIO_PROJECT_SEARCH_TABLES, AUTOMATION_STUDIO_PROJECT_MUTATION_TABLES, AUTOMATION_STUDIO_PROJECT_STREAM_SPOOL_TABLES } from "./table-names.ts";
