// 0003 — uniqueness and lookup indexes, full-text and r-tree search tables,
// and the relationship guards for the domain resources.
import type { AutomationStudioSchemaMigration } from "../../schema-migrations.ts";
import { foreignKeyGuards } from "./foreign-key-guards.ts";

export const AUTOMATION_STUDIO_PROJECT_RELATION_INDEX_MIGRATION: AutomationStudioSchemaMigration = {
  id: "0003_relation_indexes_search",
  statements: [
    "create unique index graph_partitions_flow_grid_uq on graph_partitions (flow_id, grid_x, grid_y)",
    "create unique index graph_revisions_flow_revision_uq on graph_revisions (flow_id, revision_number)",
    "create unique index graph_operations_revision_ordinal_uq on graph_operations (revision_id, ordinal)",
    "create unique index subflows_graph_flow_uq on subflows (graph_flow_id)",
    "create unique index routers_flow_uq on routers (flow_id)",
    "create unique index runtime_event_chunks_run_first_uq on runtime_event_chunks (run_id, first_sequence)",
    "create unique index recording_event_chunks_recording_first_uq on recording_event_chunks (recording_id, first_sequence)",
    "create unique index objects_sha256_uq on objects (sha256)",
    "create unique index object_references_owner_uq on object_references (object_id, owner_kind, owner_id, purpose)",
    "create unique index flow_publications_flow_version_uq on flow_publications (flow_id, version)",
    "create unique index compiled_artifacts_flow_revision_compiler_uq on compiled_artifacts (flow_id, flow_revision, compiler_version)",
    "create unique index flow_ports_flow_direction_name_uq on flow_ports (flow_id, direction, name)",
    "create unique index flow_variables_flow_name_uq on flow_variables (flow_id, name)",
    "create unique index flow_errors_flow_code_uq on flow_errors (flow_id, code)",
    "create index hierarchy_entries_children_idx on hierarchy_entries (parent_entry_id, is_deleted, sort_key, entry_id)",
    "create index hierarchy_entries_owner_idx on hierarchy_entries (owner_id, kind)",
    "create index hierarchy_entries_path_idx on hierarchy_entries (path_key)",
    "create index flows_parent_status_idx on flows (parent_flow_id, status, updated_at_ms desc, flow_id)",
    "create index flows_updated_idx on flows (updated_at_ms desc, flow_id desc)",
    "create index graph_nodes_partition_idx on graph_nodes (flow_id, partition_id, deleted_at_ms, node_id)",
    "create index graph_nodes_definition_idx on graph_nodes (flow_id, definition_id, deleted_at_ms, node_id)",
    "create index graph_edges_source_idx on graph_edges (flow_id, source_node_id, deleted_at_ms, edge_id)",
    "create index graph_edges_target_idx on graph_edges (flow_id, target_node_id, deleted_at_ms, edge_id)",
    "create index graph_operations_entity_idx on graph_operations (entity_kind, entity_id, revision_id)",
    "create index subflows_parent_status_name_idx on subflows (parent_flow_id, status, name collate nocase, subflow_id)",
    "create index subflows_category_idx on subflows (parent_category_id, status, name collate nocase, subflow_id)",
    "create index subflow_categories_children_idx on subflow_categories (flow_id, parent_category_id, sort_key, category_id)",
    "create index router_routes_priority_idx on router_routes (router_id, enabled, priority desc, route_id)",
    "create index instruction_scopes_lookup_idx on instruction_scopes (scope_kind, project_id, flow_id, router_id, subflow_id, node_id, error_code)",
    "create index instruction_bindings_owner_idx on instruction_bindings (owner_kind, owner_id, enabled, sort_key, binding_id)",
    "create index runtime_runs_started_idx on runtime_runs (started_at_ms desc, run_id desc)",
    "create index runtime_runs_flow_status_idx on runtime_runs (flow_id, status, started_at_ms desc, run_id desc)",
    "create index runtime_event_chunks_sequence_idx on runtime_event_chunks (run_id, first_sequence, last_sequence)",
    "create index recordings_time_idx on recordings (started_at_ms desc, recording_id desc)",
    "create index recording_event_chunks_sequence_idx on recording_event_chunks (recording_id, first_sequence, last_sequence)",
    "create index state_snapshots_source_idx on state_snapshots (source_kind, source_id, sequence)",
    "create index state_paths_lookup_idx on state_paths (namespace, path, value_type)",
    "create index adaptations_flow_status_idx on adaptations (flow_id, status, updated_at_ms desc, adaptation_id)",
    "create index adaptations_subflow_status_idx on adaptations (subflow_id, status, updated_at_ms desc, adaptation_id)",
    "create index object_references_owner_idx on object_references (owner_kind, owner_id, purpose)",
    "create virtual table hierarchy_entries_fts using fts5(entry_id unindexed, display_name)",
    "create virtual table graph_nodes_fts using fts5(node_id unindexed, flow_id unindexed, label, description)",
    "create virtual table instructions_fts using fts5(instruction_id unindexed, title, inline_body)",
    "create virtual table graph_node_bounds using rtree(bounds_id, min_x, max_x, min_y, max_y)",
    "create table graph_node_bounds_map (bounds_id integer primary key, node_id text not null unique)",
    `create trigger graph_nodes_bounds_ai after insert on graph_nodes when new.deleted_at_ms is null begin
      insert into graph_node_bounds_map (bounds_id, node_id) values (new.rowid, new.node_id);
      insert into graph_node_bounds (bounds_id, min_x, max_x, min_y, max_y) values (new.rowid, new.x, new.x + new.width, new.y, new.y + new.height);
    end`,
    `create trigger graph_nodes_bounds_ad after delete on graph_nodes begin
      delete from graph_node_bounds where bounds_id = old.rowid;
      delete from graph_node_bounds_map where bounds_id = old.rowid;
    end`,
    `create trigger graph_nodes_bounds_au_clear after update on graph_nodes begin
      delete from graph_node_bounds where bounds_id = old.rowid;
      delete from graph_node_bounds_map where bounds_id = old.rowid;
    end`,
    `create trigger graph_nodes_bounds_au_insert after update on graph_nodes when new.deleted_at_ms is null begin
      insert into graph_node_bounds_map (bounds_id, node_id) values (new.rowid, new.node_id);
      insert into graph_node_bounds (bounds_id, min_x, max_x, min_y, max_y) values (new.rowid, new.x, new.x + new.width, new.y, new.y + new.height);
    end`,
    ...foreignKeyGuards("flows", "parent_flow_id", "flows", "flow_id"),
    ...foreignKeyGuards("flows", "owning_subflow_id", "subflows", "subflow_id"),
    ...foreignKeyGuards("flow_settings", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("flow_ports", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("flow_variables", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("flow_errors", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("graph_partitions", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("graph_nodes", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("graph_nodes", "partition_id", "graph_partitions", "partition_id"),
    ...foreignKeyGuards("graph_edges", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("graph_edges", "source_node_id", "graph_nodes", "node_id", false),
    ...foreignKeyGuards("graph_edges", "target_node_id", "graph_nodes", "node_id", false),
    ...foreignKeyGuards("flow_regions", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("flow_regions", "partition_id", "graph_partitions", "partition_id"),
    ...foreignKeyGuards("flow_region_handoffs", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("flow_region_handoffs", "from_region_id", "flow_regions", "region_id", false),
    ...foreignKeyGuards("flow_region_handoffs", "to_region_id", "flow_regions", "region_id", false),
    ...foreignKeyGuards("graph_revisions", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("graph_revisions", "snapshot_object_id", "objects", "object_id"),
    ...foreignKeyGuards("graph_operations", "revision_id", "graph_revisions", "revision_id", false),
    ...foreignKeyGuards("subflows", "parent_flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("subflows", "graph_flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("subflows", "parent_category_id", "subflow_categories", "category_id"),
    ...foreignKeyGuards("subflow_categories", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("subflow_categories", "parent_category_id", "subflow_categories", "category_id"),
    ...foreignKeyGuards("routers", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("routers", "fallback_subflow_id", "subflows", "subflow_id"),
    ...foreignKeyGuards("router_groups", "router_id", "routers", "router_id", false),
    ...foreignKeyGuards("router_routes", "router_id", "routers", "router_id", false),
    ...foreignKeyGuards("router_routes", "group_id", "router_groups", "group_id"),
    ...foreignKeyGuards("router_routes", "target_subflow_id", "subflows", "subflow_id"),
    ...foreignKeyGuards("instructions", "body_object_id", "objects", "object_id"),
    ...foreignKeyGuards("instruction_scopes", "instruction_id", "instructions", "instruction_id", false),
    ...foreignKeyGuards("instruction_scopes", "flow_id", "flows", "flow_id"),
    ...foreignKeyGuards("instruction_scopes", "router_id", "routers", "router_id"),
    ...foreignKeyGuards("instruction_scopes", "subflow_id", "subflows", "subflow_id"),
    ...foreignKeyGuards("instruction_scopes", "node_id", "graph_nodes", "node_id"),
    ...foreignKeyGuards("instruction_tags", "instruction_id", "instructions", "instruction_id", false),
    ...foreignKeyGuards("instruction_bindings", "instruction_id", "instructions", "instruction_id", false),
    ...foreignKeyGuards("effective_instruction_cache", "object_id", "objects", "object_id", false),
    ...foreignKeyGuards("runtime_runs", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("runtime_runs", "compiled_artifact_id", "compiled_artifacts", "artifact_id"),
    ...foreignKeyGuards("runtime_runs", "input_object_id", "objects", "object_id"),
    ...foreignKeyGuards("runtime_runs", "output_object_id", "objects", "object_id"),
    ...foreignKeyGuards("runtime_runs", "error_object_id", "objects", "object_id"),
    ...foreignKeyGuards("runtime_event_chunks", "run_id", "runtime_runs", "run_id", false),
    ...foreignKeyGuards("runtime_event_chunks", "object_id", "objects", "object_id", false),
    ...foreignKeyGuards("recordings", "thumbnail_object_id", "objects", "object_id"),
    ...foreignKeyGuards("recording_event_chunks", "recording_id", "recordings", "recording_id", false),
    ...foreignKeyGuards("recording_event_chunks", "object_id", "objects", "object_id", false),
    ...foreignKeyGuards("state_snapshots", "state_object_id", "objects", "object_id"),
    ...foreignKeyGuards("state_snapshots", "screenshot_object_id", "objects", "object_id"),
    ...foreignKeyGuards("state_snapshots", "previous_snapshot_id", "state_snapshots", "snapshot_id"),
    ...foreignKeyGuards("state_paths", "snapshot_id", "state_snapshots", "snapshot_id", false),
    ...foreignKeyGuards("state_paths", "value_object_id", "objects", "object_id"),
    ...foreignKeyGuards("adaptations", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("adaptations", "subflow_id", "subflows", "subflow_id"),
    ...foreignKeyGuards("adaptations", "patch_object_id", "objects", "object_id", false),
    ...foreignKeyGuards("adaptations", "evidence_object_id", "objects", "object_id"),
    ...foreignKeyGuards("adaptation_evidence", "adaptation_id", "adaptations", "adaptation_id", false),
    ...foreignKeyGuards("flow_publications", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("flow_publications", "compiled_artifact_id", "compiled_artifacts", "artifact_id"),
    ...foreignKeyGuards("compiled_artifacts", "flow_id", "flows", "flow_id", false),
    ...foreignKeyGuards("compiled_artifacts", "object_id", "objects", "object_id", false),
    ...foreignKeyGuards("object_references", "object_id", "objects", "object_id", false)
  ]
};
