"use client";

import type { JsonObject } from "../../programs/program-api";
import type { AutomationDockTab, AutomationSelection, AutomationViewInstance } from "../types";
import { AutomationAssistantView, AutomationClientGatewayView, AutomationConfigView } from "./ClientViews";
import { AutomationPipelineView } from "./PipelineView";
import { AutomationTimelineView } from "./TimelineView";
import { AutomationInspector } from "./InspectorView";
import { AutomationPolicyCanvas, AutomationRoutineView, AutomationStateExplorerView, AutomationWorkspaceDock } from "./GraphEditorViews";
import { AutomationProblemsWorkspace, AutomationRecordingWorkspace, AutomationRunsWorkspace, AutomationRuntimeWorkspace, AutomationSignalWorkspace } from "./WorkspaceViews";
export function AutomationViewRenderer(props: {
  actionStatus: string;
  entries: any[];
  models: any[];
  notes: any[];
  policies: any[];
  pipelineArtifacts: any;
  policy: any;
  problems: any[];
  projectId: string | null;
  recordings: any[];
  recordingDomains: any[];
  runtimeSessions: any[];
  dockTab: AutomationDockTab;
  selectedEntry: any;
  selectedNode: any;
  selectedRecording: any;
  selectedSignal: any;
  selectedTimeline: any;
  selection: AutomationSelection | null;
  signals: any[];
  timelines: any[];
  view: AutomationViewInstance;
  onDeleteRecording(recordingId: string): Promise<void>;
  onFinalizeRecording(recordingId: string): Promise<void>;
  onOpenPipeline(recordingId: string): void;
  onOpenRecording(recordingId: string): void;
  onAppendRecordingMarker(recordingId: string, linkedEntryId?: string, monotonicOffsetMs?: number): Promise<void>;
  onAppendRecordingNote(recordingId: string, linkedEntryId?: string): Promise<void>;
  onNormalizeRecording(recordingId: string): Promise<void>;
  onPipelineAction(endpoint: string, payload: JsonObject, success: string): Promise<void>;
  onRunRecordingPipeline(recordingId: string): Promise<void>;
  onProcessProposalWithLlm(proposalId: string): void;
  onRefreshRecordings(): Promise<void>;
  onUpdateRecording(recordingId: string, changes: JsonObject): Promise<void>;
  setDockTab(tab: AutomationDockTab): void;
  setSelection(selection: AutomationSelection): void;
}) {
  if (props.view.type === "design") return <AutomationPolicyCanvas entries={props.entries} policy={props.policy} recordings={props.recordings} selectedNode={props.selectedNode} selectedTimeline={props.selectedTimeline} signals={props.signals} setSelection={props.setSelection} />;
  if (props.view.type === "recordings") return <AutomationTimelineView actionStatus={props.actionStatus} entries={props.entries} notes={props.notes} recordings={props.recordings} selectedEntry={props.selectedEntry} selectedRecording={props.selectedRecording} selectedTimeline={props.selectedTimeline} timelines={props.timelines} onAppendRecordingMarker={props.onAppendRecordingMarker} onAppendRecordingNote={props.onAppendRecordingNote} onDeleteRecording={props.onDeleteRecording} onFinalizeRecording={props.onFinalizeRecording} onOpenPipeline={props.onOpenPipeline} onRefreshRecordings={props.onRefreshRecordings} onUpdateRecording={props.onUpdateRecording} setSelection={props.setSelection} />;
  if (props.view.type === "pipeline") return <AutomationPipelineView actionStatus={props.actionStatus} models={props.models} pipelineArtifacts={props.pipelineArtifacts} recordings={props.recordings} selectedRecording={props.selectedRecording} selectedTimeline={props.selectedTimeline} timelines={props.timelines} onNormalizeRecording={props.onNormalizeRecording} onOpenRecording={props.onOpenRecording} onPipelineAction={props.onPipelineAction} onProcessProposalWithLlm={props.onProcessProposalWithLlm} onRunRecordingPipeline={props.onRunRecordingPipeline} />;
  if (props.view.type === "signals") return <AutomationSignalWorkspace domains={props.recordingDomains} signals={props.signals} setSelection={props.setSelection} />;
  if (props.view.type === "runtime") return <AutomationRuntimeWorkspace pipelineArtifacts={props.pipelineArtifacts} timelines={props.selectedTimeline ? [props.selectedTimeline] : []} models={props.models} policies={props.policies} runtimeSessions={props.runtimeSessions} />;
  if (props.view.type === "runs") return <AutomationRunsWorkspace pipelineArtifacts={props.pipelineArtifacts} runtimeSessions={props.runtimeSessions} />;
  if (props.view.type === "clients") return <AutomationClientGatewayView projectId={props.projectId} />;
  if (props.view.type === "problems") return <AutomationProblemsWorkspace problems={props.problems} />;
  if (props.view.type === "assistant") return <AutomationAssistantView node={props.selectedNode} recording={props.selectedRecording} signals={props.signals} />;
  if (props.view.type === "inspector") return <AutomationInspector entries={props.entries} selection={props.selection} policy={props.policy} node={props.selectedNode} recording={props.selectedRecording} entry={props.selectedEntry} signal={props.selectedSignal} setSelection={props.setSelection} />;
  if (props.view.type === "dock") return <AutomationWorkspaceDock activeTab={props.dockTab} problems={props.problems} signals={props.signals} models={props.models} selectedNode={props.selectedNode} setActiveTab={props.setDockTab} />;
  if (props.view.type === "routine") return <AutomationRoutineView models={props.models} policies={props.policies} setSelection={props.setSelection} />;
  if (props.view.type === "config") return <AutomationConfigView policy={props.policy} />;
  return <AutomationStateExplorerView signals={props.signals} entries={props.entries} setSelection={props.setSelection} />;
}
