// Two candidate submissions exactly as live builds sent them (2026-10-08), each
// call's `input.flow` copied whole, so a refusal is tested on the text that met
// it rather than on a script written to pass.
//
// Lane B, `run-mv0fu9pb-57454dc4` step 0058: refused for two steps that type a
// search and send it (`submit: true`, lines 32 and 58) with no `consequences:`
// line. Its four `optional: yes` steps each assemble into two nodes, so the
// refusal's plan paths (nodes 10 and 17) named no step the model could find.
//
// Lane C, `run-mv0fuotv-805294d7` step 0036: `repeat while: next` on the
// listing, and `repeat most: 10` under `next`, the span's last step -- refused
// as a repeat inside a repeat until a bound under a member was read as the
// span's own.

/** Lane B's submitted script (`input.flow`). */
export const LANE_B_SUBMITTED_FLOW = "flow: Switch pickup store to Millbrook Crossing and add paper towels and dinner napkins for pickup\nstep: open the store's home page\n  node: web.browser-navigate\n  url: http://127.0.0.1:62535/scenarios/bigbox-retail/\nstep: dismiss the privacy choices banner if it shows\n  node: web.dom-click\n  target: t317\n  consequences: none\n  optional: yes\nstep: dismiss the email signup offer if it shows\n  node: web.dom-click\n  target: t332\n  consequences: none\n  optional: yes\nstep: dismiss the chat panel if it shows\n  node: web.dom-click\n  target: t324\n  consequences: none\n  optional: yes\nstep: open the store picker\n  node: web.dom-click\n  target: t7\n  consequences: none\nstep: choose Millbrook Crossing Supercenter\n  node: web.dom-click\n  target: t340\n  consequences: none\nstep: set it as my store\n  node: web.dom-click\n  target: t343\n  consequences: modify_existing\nstep: search for the paper towels\n  node: web.dom-type\n  target: t11\n  text: ValueRidge Essentials Select-A-Size Paper Towels\n  submit: true\nstep: open the paper towels product\n  node: web.dom-click\n  target: t1246\n  consequences: none\nstep: choose the 12 Double Rolls size\n  node: web.dom-check\n  target: t551\n  checked: true\nstep: set the quantity to two packs\n  node: web.dom-type\n  target: t560\n  text: 2\nstep: add the paper towels to the cart\n  node: web.dom-click\n  target: t570\n  consequences: modify_existing\nstep: continue shopping after adding\n  node: web.dom-click\n  target: t1136\n  consequences: none\n  optional: yes\nstep: search for the dinner napkins\n  node: web.dom-type\n  target: t11\n  text: ValueRidge Everyday Dinner Napkins 250 Count\n  submit: true\nstep: open the napkins product\n  node: web.dom-click\n  target: t1246\n  consequences: none\nstep: add the napkins to the cart\n  node: web.dom-click\n  target: t1440\n  consequences: modify_existing\nstep: continue shopping after adding the napkins\n  node: web.dom-click\n  target: t1136\n  consequences: none\n  optional: yes";

/** Lane B's submitted summary (`input.summary`). */
export const LANE_B_SUBMITTED_SUMMARY = "Switch pickup store to Millbrook Crossing Supercenter, add two packs of ValueRidge Essentials Select-A-Size Paper Towels 12 Double Rolls and one pack of ValueRidge Everyday Dinner Napkins 250 Count for pickup, keeping the existing cart.";

/** Lane C's submitted script (`input.flow`); it sent no summary. */
export const LANE_C_SUBMITTED_FLOW = "flow: List Brightaisle Plus wireless earbuds rated 4.0+ under $50 across all search result pages\nstep: open the wireless earbuds search\n  node: web.browser-navigate\n  url: http://127.0.0.1:60760/scenarios/everything-store/s?k=wireless+earbuds\nstep: close the cookie banner if it shows\n  node: web.dom-click\n  target: t37\n  consequences: none\n  optional: yes\nstep page: read this page of results\n  node: web.dom-extract_list\n  extractList: extraction.1\n  extractList.fields.name: div_css-1h13pfs_h2_css-0lh1x1m_a_css-1ahy6rs_span\n  extractList.fields.price: div_css-1h13pfs_div_itemprop_offers_a_css-1wwnizn_span_css-00egoa7_span_css-1f32dgn_currency_amount\n  extractList.fields.rating: div_css-1h13pfs_div_css-1bc9pgf_span_css-11xfgav_span_css-14idg5p_number\n  extractList.fields.url: div_css-1h13pfs_h2_css-0lh1x1m_a_css-1ahy6rs_url@href\n  extractList.fields.sponsored: div_css-1f5vozn_span\n  extractList.fields.plus: brightaisle_plus\n  extractList.minItems: 0\n  recordOutput.columns: [\"name\", \"price\", \"rating\", \"url\"]\n  recordOutput.process: {\"where\": [{\"field\": \"sponsored\", \"is\": \"absent\"}, {\"field\": \"plus\", \"is\": \"present\"}, {\"field\": \"rating\", \"atLeast\": 4.0}, {\"field\": \"price\", \"lessThan\": 50}, {\"field\": \"name\", \"contains\": [\"ear tips\", \"charging case\", \"eartips\"], \"not\": true}], \"dedupe\": \"name\"}\n  repeat while: next\nstep next: go to the next page\n  node: web.dom-next_page\n  nextPage: extraction.1\n  consequences: none\n  repeat most: 10";
